### ISSUE TITLE
クイックスタートガイドに従ってのアプリケーション構築時、ログインができない

### ISSUE THREAD

**Issue by ibuzu** [sitoolkit/sit-ad-archetype#2]
クイックスタートガイドで指定いただいている、ユーザ名/パスワードで、ログインができません。

**Comment by ykuwahara** [comment]
投稿ありがとうございます。

使っているPCにはCドライブ、Dドライブの様に複数のドライブがありますか？
そうであれば以下を試して貰えますか？
 
1. _project_root_ \sit\bin\as\02_run-script-gfembed.cmdをテキストエディタで開きます。

2. 92行目のKEYFILE_DIRに「C:」を追加します。

<pre>
set KEYFILE_DIR=\dev\oracle\embedded-glassfish\%CTX_ROOT%
 ↓
set KEYFILE_DIR=C:\dev\oracle\embedded-glassfish\%CTX_ROOT%
</pre>

3. 変更内容を保存します。

4. _project_root_ \sit\bin\as\30_deploy.cmdをダブルクリックで実行します。

5. クイックスタートの手順と同様に、 _project_root_ \sitb\open-site.cmdをダブルクリックで実行し、ブラウザに表示されたWebアプリケーションへのログインを試します。

**Comment by ibuzu** [comment]
回答ありがとうございます。

使っているPCは、Cドライブのみの構成ですが、回答いただいた手順にて、ログイン可能となりました。

ありがとうございます。
